bundle_root: .
data_dir: .
data_list_file: .
dataset_json:
  channel_names:
    '0': CT
  file_ending: .nii.gz
  labels:
    background: 0
    class1: 1
  numTraining: 41
device: $torch.device('cuda')
fold_id: 0
image_key: image
image_modality_keys: $list(@modality_conf.keys())
image_suffix: '@image_key'
imports:
- $import json
- $from pathlib import Path
- $import os
- $from ignite.contrib.handlers.tqdm_logger import ProgressBar
- $import shutil
- $import src
- $import src.dataset
inferer:
  _target_: SimpleInferer
modality_conf:
  image:
    suffix: .nii.gz
model_name: model.pt
network_def: $monai.apps.nnunet.nnunet_bundle.get_nnunet_monai_predictor(**@nnunet_config_dict)
network_def_predictor: $@network_def.network_weights
nnunet_config_ckpt:
  configuration: 3d_fullres
  inference_allowed_mirroring_axes:
  - 0
  - 1
  - 2
  trainer_name: '@nnunet_trainer_class_name'
nnunet_config_dict:
  dataset_json: '@dataset_json'
  model_folder: $@bundle_root + '/models/fold_'+str(@fold_id)
  model_name: '@model_name'
  nnunet_config: '@nnunet_config_ckpt'
  plans: '@plans'
nnunet_trainer_class_name: nnUNetTrainer
output_dir: .
plans:
  configurations:
    2d:
      architecture:
        _kw_requires_import:
        - conv_op
        - norm_op
        - dropout_op
        - nonlin
        arch_kwargs:
          conv_bias: true
          conv_op: torch.nn.modules.conv.Conv2d
          dropout_op: null
          dropout_op_kwargs: null
          features_per_stage:
          - 32
          - 64
          - 128
          - 256
          - 512
          - 512
          - 512
          - 512
          kernel_sizes:
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          - - 3
            - 3
          n_conv_per_stage:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          n_conv_per_stage_decoder:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          n_stages: 8
          nonlin: torch.nn.LeakyReLU
          nonlin_kwargs:
            inplace: true
          norm_op: torch.nn.modules.instancenorm.InstanceNorm2d
          norm_op_kwargs:
            affine: true
            eps: 1.0e-05
          strides:
          - - 1
            - 1
          - - 2
            - 2
          - - 2
            - 2
          - - 2
            - 2
          - - 2
            - 2
          - - 2
            - 2
          - - 2
            - 2
          - - 2
            - 2
        network_class_name: dynamic_network_architectures.architectures.unet.PlainConvUNet
      batch_dice: true
      batch_size: 12
      data_identifier: nnUNetPlans_2d
      median_image_size_in_voxels:
      - 512.0
      - 512.0
      normalization_schemes:
      - CTNormalization
      patch_size:
      - 512
      - 512
      preprocessor_name: DefaultPreprocessor
      resampling_fn_data: resample_data_or_seg_to_shape
      resampling_fn_data_kwargs:
        force_separate_z: null
        is_seg: false
        order: 3
        order_z: 0
      resampling_fn_probabilities: resample_data_or_seg_to_shape
      resampling_fn_probabilities_kwargs:
        force_separate_z: null
        is_seg: false
        order: 1
        order_z: 0
      resampling_fn_seg: resample_data_or_seg_to_shape
      resampling_fn_seg_kwargs:
        force_separate_z: null
        is_seg: true
        order: 1
        order_z: 0
      spacing:
      - 0.7929689884185791
      - 0.7929689884185791
      use_mask_for_norm:
      - false
    3d_cascade_fullres:
      inherits_from: 3d_fullres
      previous_stage: 3d_lowres
    3d_fullres:
      architecture:
        _kw_requires_import:
        - conv_op
        - norm_op
        - dropout_op
        - nonlin
        arch_kwargs:
          conv_bias: true
          conv_op: torch.nn.modules.conv.Conv3d
          dropout_op: null
          dropout_op_kwargs: null
          features_per_stage:
          - 32
          - 64
          - 128
          - 256
          - 320
          - 320
          kernel_sizes:
          - - 1
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          n_conv_per_stage:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          n_conv_per_stage_decoder:
          - 2
          - 2
          - 2
          - 2
          - 2
          n_stages: 6
          nonlin: torch.nn.LeakyReLU
          nonlin_kwargs:
            inplace: true
          norm_op: torch.nn.modules.instancenorm.InstanceNorm3d
          norm_op_kwargs:
            affine: true
            eps: 1.0e-05
          strides:
          - - 1
            - 1
            - 1
          - - 1
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
        network_class_name: dynamic_network_architectures.architectures.unet.PlainConvUNet
      batch_dice: true
      batch_size: 2
      data_identifier: nnUNetPlans_3d_fullres
      median_image_size_in_voxels:
      - 187.0
      - 512.0
      - 512.0
      normalization_schemes:
      - CTNormalization
      patch_size:
      - 64
      - 192
      - 160
      preprocessor_name: DefaultPreprocessor
      resampling_fn_data: resample_data_or_seg_to_shape
      resampling_fn_data_kwargs:
        force_separate_z: null
        is_seg: false
        order: 3
        order_z: 0
      resampling_fn_probabilities: resample_data_or_seg_to_shape
      resampling_fn_probabilities_kwargs:
        force_separate_z: null
        is_seg: false
        order: 1
        order_z: 0
      resampling_fn_seg: resample_data_or_seg_to_shape
      resampling_fn_seg_kwargs:
        force_separate_z: null
        is_seg: true
        order: 1
        order_z: 0
      spacing:
      - 1.6000100374221802
      - 0.7929689884185791
      - 0.7929689884185791
      use_mask_for_norm:
      - false
    3d_lowres:
      architecture:
        _kw_requires_import:
        - conv_op
        - norm_op
        - dropout_op
        - nonlin
        arch_kwargs:
          conv_bias: true
          conv_op: torch.nn.modules.conv.Conv3d
          dropout_op: null
          dropout_op_kwargs: null
          features_per_stage:
          - 32
          - 64
          - 128
          - 256
          - 320
          - 320
          kernel_sizes:
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          - - 3
            - 3
            - 3
          n_conv_per_stage:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          n_conv_per_stage_decoder:
          - 2
          - 2
          - 2
          - 2
          - 2
          n_stages: 6
          nonlin: torch.nn.LeakyReLU
          nonlin_kwargs:
            inplace: true
          norm_op: torch.nn.modules.instancenorm.InstanceNorm3d
          norm_op_kwargs:
            affine: true
            eps: 1.0e-05
          strides:
          - - 1
            - 1
            - 1
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 2
            - 2
            - 2
          - - 1
            - 2
            - 2
        network_class_name: dynamic_network_architectures.architectures.unet.PlainConvUNet
      batch_dice: false
      batch_size: 2
      data_identifier: nnUNetPlans_3d_lowres
      median_image_size_in_voxels:
      - 110
      - 292
      - 292
      next_stage: 3d_cascade_fullres
      normalization_schemes:
      - CTNormalization
      patch_size:
      - 64
      - 192
      - 192
      preprocessor_name: DefaultPreprocessor
      resampling_fn_data: resample_data_or_seg_to_shape
      resampling_fn_data_kwargs:
        force_separate_z: null
        is_seg: false
        order: 3
        order_z: 0
      resampling_fn_probabilities: resample_data_or_seg_to_shape
      resampling_fn_probabilities_kwargs:
        force_separate_z: null
        is_seg: false
        order: 1
        order_z: 0
      resampling_fn_seg: resample_data_or_seg_to_shape
      resampling_fn_seg_kwargs:
        force_separate_z: null
        is_seg: true
        order: 1
        order_z: 0
      spacing:
      - 2.7239099860232163
      - 1.390475921094405
      - 1.390475921094405
      use_mask_for_norm:
      - false
  dataset_name: Dataset009_Task09_Spleen
  experiment_planner_used: ExperimentPlanner
  foreground_intensity_properties_per_channel:
    '0':
      max: 1038.0
      mean: 93.1926498413086
      median: 97.0
      min: -620.0
      percentile_00_5: -42.0
      percentile_99_5: 176.0
      std: 40.78365707397461
  image_reader_writer: SimpleITKIO
  label_manager: LabelManager
  original_median_shape_after_transp:
  - 90
  - 512
  - 512
  original_median_spacing_after_transp:
  - 5.0
  - 0.7929689884185791
  - 0.7929689884185791
  plans_name: nnUNetPlans
  transpose_backward:
  - 0
  - 1
  - 2
  transpose_forward:
  - 0
  - 1
  - 2
postprocessing:
  _target_: Compose
  transforms:
  - _target_: SaveImaged
    keys: pred
    meta_keys: image_meta_dict
    output_dir: '@output_dir'
    output_postfix: '@prediction_suffix'
    resample: false
prediction_suffix: prediction
preprocessing:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    ensure_channel_first: true
    image_only: false
    keys: image
run:
- $@testing#pbar.attach(@validator)
- $@validator.run()
test_data_list: $src.dataset.get_subfolder_dataset(@data_dir,@modality_conf)
test_dataset:
  _target_: Dataset
  data: $@test_data_list
  transform: '@preprocessing'
test_loader:
  _target_: DataLoader
  batch_size: 1
  dataset: '@test_dataset'
testing:
  dataloader: $@test_loader
  pbar:
    _target_: ignite.contrib.handlers.tqdm_logger.ProgressBar
  test_inferer: $@inferer
validator:
  _target_: SupervisedEvaluator
  device: $@device
  inferer: $@testing#test_inferer
  network: '@network_def'
  postprocessing: $@postprocessing
  val_data_loader: $@testing#dataloader
  val_handlers:
  - _target_: CheckpointLoader
    load_dict:
      network_weights: $@network_def.network_weights
    load_path: $@bundle_root+'/models/fold_'+str(@fold_id)+'/'+@model_name
